name: Update README file
on:
  schedule:
    - cron: '0 0 * * *' # Runs every day
  workflow_dispatch:
jobs:
  update-codepen:
    name: Update this repo's README with pens from Codepen
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "CODEPEN"
          disable_sort: true
          date_format: "mmm d, yyyy"
          commit_message: "Update Codepen list"
          item_exec: |
            // images don't work, needs to push the images to reference them
            post.description = post.description.match(/src="([^"]+)"/)[1] || '';
          template: |
            $newline - [$title]($url) $newline
          feed_list: "https://codepen.io/collection/OLyaME/feed"
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "STACKOVERFLOW"
          disable_sort: true
          date_format: "mmm d, yyyy"
          commit_message: "Update StackOverflow list"
          template: "$newline- [$title]($url)"
          feed_list: "https://stackoverflow.com/feeds/user/1899195"
